export type iconTypes =
  | 'ChatTeardropDots'
  | 'CreditCard'
  | 'Cube'
  | 'GearSix'
  | 'HouseSimple'
  | 'Icon'
  | 'ListBullets'
  | 'Users'
  | 'Vector (1)'
  | 'Vector'
  | 'BookmarkSimple'
  | 'DotsThreeOutlineVertical'
  | 'HouseSimple'
  | 'Monotone add (1)'
  | 'Monotone add (2)'
  | 'Monotone add (3)'
  | 'ShareFat'
  | 'ThumbsUp';
