export type iconTypes =
  | 'ChatTeardropDots'
  | 'CreditCard'
  | 'Cube'
  | 'GearSix'
  | 'HouseSimple'
  | 'Search'
  | 'ListBullets'
  | 'Users'
  | 'Vector (1)'
  | 'Vector'
  | 'BookmarkSimple'
  | 'DotsThreeOutlineVertical'
  | 'HouseSimple'
  | 'Send'
  | 'Monotone add (2)'
  | 'Monotone add (3)'
  | 'ShareFat'
  | 'ThumbsUp'
  | 'ChatDots'
  | 'BookmarkSimple'
  | 'DotsVertical'
  | 'AvataUser'
  | 'Plus'
  | 'AvatarPost'
  | 'LokkitLogo'
  | 'Warning'
  | 'X'
  | 'Message'
  | 'Reminder'
  | 'Setting'
  | 'Youtube'
  | 'Vkn'
  | 'Google'
  | 'Email'
  | 'Unlock'
  | 'UserCircle'
  | 'Exit';
